// GymOS Android -- Capacitor configuration.
//
// The APK is a native shell around the LIVE GymOS web app: it loads
// server.url instead of bundling a copy of frontend/dist. That keeps the app
// on the same origin the website runs on, so the httpOnly SameSite=strict
// session cookie, the CSP, the relative /api and /uploads paths and every
// share link behave exactly as they do in a browser, with no backend change
// and no second copy of the UI to keep in sync. mobile/README.md has the full
// reasoning and the build steps.
const PRODUCTION_URL = 'https://gym-os-nikhaar-fashions-connect.vercel.app';

// The Android emulator's alias for the host machine. The only cleartext
// origin a build may point at, and only debug builds allow it at all
// (see android/app/src/debug/res/xml/network_security_config.xml).
const EMULATOR_HOST = '10.0.2.2';

// GYMOS_SERVER_URL points a build at another deployment -- a Vercel preview,
// or a local stack for testing on the emulator. Validated here so a typo
// fails the sync instead of shipping an APK that opens the wrong site.
function resolveServerUrl() {
  const raw = (process.env.GYMOS_SERVER_URL || PRODUCTION_URL).trim().replace(/\/+$/, '');
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`GYMOS_SERVER_URL is not a valid URL: ${raw}`);
  }
  const isLocalEmulatorHost = url.protocol === 'http:' && url.hostname === EMULATOR_HOST;
  if (url.protocol !== 'https:' && !isLocalEmulatorHost) {
    throw new Error(`GYMOS_SERVER_URL must be https (or http://${EMULATOR_HOST} for local testing): ${raw}`);
  }
  if (url.pathname !== '/' || url.search || url.hash) {
    throw new Error(`GYMOS_SERVER_URL must be an origin with no path, query or hash: ${raw}`);
  }
  return url.origin;
}

module.exports = {
  appId: 'com.gymos.app',
  appName: 'GymOS',
  // Holds only the shell's own local files (offline page, injected script),
  // generated by scripts/build-www.mjs -- never the web app itself.
  webDir: 'www',
  appendUserAgent: 'GymOS-Android',
  backgroundColor: '#0A0909',
  server: {
    url: resolveServerUrl(),
    // Shown when the GymOS origin cannot be loaded (no network, outage).
    errorPath: 'offline.html',
  },
  android: {
    // The shell script is injected with WebViewCompat.addDocumentStartJavaScript,
    // and the web app's own build targets a modern Chromium; an older WebView
    // gets the offline page rather than a half-working app.
    minWebViewVersion: 90,
  },
  plugins: {
    SystemBars: {
      // GymOS has no viewport-fit=cover, so the WebView is padded clear of
      // the status bar, navigation bar and keyboard natively.
      insetsHandling: 'css',
      style: 'DARK',
    },
    GymOSShell: {
      // Hosts that open INSIDE the app instead of the external browser:
      // Razorpay checkout windows, and the WHOOP / Oura sign-in pages whose
      // OAuth callback returns to GymOS. Deliberately not server.allowNavigation,
      // which would also expose the native bridge to those third-party origins.
      inAppHosts: ['*.razorpay.com', '*.whoop.com', '*.ouraring.com'],
    },
  },
};
